### ISSUE TITLE
Critical Game Bug Dev Build comzombies-Universal-2.2.65.jar

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#67] opened 2021-01-31 23:20 UTC
An issues occurs when the last player goes down in a multiplayer game. 
It teleports all the players back to their original locations
When these players try to join a fresh match they get this quote
"You are not allowed to use commands in game!"
The arena stays closed as if its in play and the only way for it to reset is for all players to disconnect or perform
/z leave

![unknown](https://user-images.githubusercontent.com/67713088/106401222-d4f9cc80-641a-11eb-966c-041ff9a62676.png)
![unknown](https://user-images.githubusercontent.com/67713088/106401227-daefad80-641a-11eb-9e12-6dceee86f428.png)

Using Spigot 1.16
Latest Dev Build - comzombies-Universal-2.2.65.jar

**Comment by TheTurkeyDev** [comment] 2021-02-01 03:04
Duplicate of #49

**Closed by TheTurkeyDev** 2021-02-01 03:04 UTC
