### ISSUE TITLE
"Enhancement Idea" Don't take gun slot 2 by default when hand isn't a gun

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#92] opened 2021-03-12 17:18 UTC
"Make it so players need to hold a gun slot to take weapons/buy them rather than default replacing slot 2 on interact as it makes a player remove a gun by mistake

**Comment by TheTurkeyDev** [comment] 2021-03-16 04:19
Dupe of #87

**Closed by TheTurkeyDev** 2021-03-16 04:19 UTC
Labels: Issue Accepted, enhancement
