### ISSUE TITLE
Hellhounds Spawn in areas players can't reach

### ISSUE THREAD

**Issue by Superfudge247** [TheTurkeyDev/Call_Of_Minecraft-Zombies#58] opened 2021-01-31 22:48 UTC
Hellhounds spawn in areas players can't reach they can spawn as many as 30 blocks away and as close and 10 blocks but depending on the size of the average map makers room this means they spawn in rooms that ain't open or yet reachable I'd suggest maybe making it so they use a similar method to zombie spawns however I am no master coder xD

Using Spigot 1.16
COMZ DEV comzombies-Universal-2.2.65.jar

**Comment by TheTurkeyDev** [comment] 2021-02-01 02:59
Duplicate of #22 Seems this still isn't 100%

**Closed by TheTurkeyDev** 2021-02-01 02:59 UTC
